# Generated by Django 2.0.1 on 2018-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'To do'), ('2', 'Doing'), ('3', 'Done')], default='1', max_length=1),
        ),
    ]
